# tasks file for lab.base-sys
---
- name: 1- Repos configuration
  import_tasks: configure_repos.yml
- name: 2- Environment configuration
  import_tasks: configure_env.yml
- name: 3- Packages installation
  import_tasks: install_packages.yml
# - name: 4- Network configuration
#   import_tasks: configure_env.yml


## ssh config, enable password
#- name: enable password authentication for ssh
  #shell: |
    #sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
  #notify: restart_sshd
##
## package [client side]
##

## starting the firewalld
#- name: start/enable firewalld
  #service: name=firewalld state=started enabled=yes
